namespace BACSender.Base.Enums
{
    public static class BacnetDicationarys
    {
        //These values are (manually) transferred from
        //http://www.bacnet.org/VendorID/BACnet Vendor IDs.htm
        //Version: "As of March 24, 2022"

        // important 260 : BACnet Stack at SourceForge
        public static Dictionary<Int16, string> BacnetVendorIdentifier = new Dictionary<Int16, string>
        {   { 0,"ASHRAE"},
            { 1, "NIST" },
            { 2, "The Trane Company" },
            { 3, "McQuay International" },
            { 4, "PolarSoft" },
            { 5, "Johnson Controls, Inc." },
            { 6, "American Auto-Matrix" },
            { 7, "Siemens Schweiz AG (Formerly: Landis & Staefa Division Europe)" },
            { 8, "Delta Controls" },
            { 9, "Siemens Schweiz AG" },
            { 10, "Schneider Electric" },
            { 11, "TAC" },
            { 12, "Orion Analysis Corporation" },
            { 13, "Teletrol Systems Inc." },
            { 14, "Cimetrics Technology" },
            { 15, "Cornell University" },
            { 16, "United Technologies Carrier" },
            { 17, "Honeywell Inc." },
            { 18, "Alerton / Honeywell" },
            { 19, "TAC AB" },
            { 20, "Hewlett-Packard Company" },
            { 21, "Dorsette's Inc." },
            { 22, "Siemens Schweiz AG (Formerly: Cerberus AG)" },
            { 23, "York Controls Group" },
            { 24, "Automated Logic Corporation" },
            { 25, "CSI Control Systems International" },
            { 26, "Phoenix Controls Corporation" },
            { 27, "Innovex Technologies, Inc." },
            { 28, "KMC Controls, Inc." },
            { 29, "Xn Technologies, Inc." },
            { 30, "Hyundai Information Technology Co., Ltd." },
            { 31, "Tokimec Inc." },
            { 32, "Simplex" },
            { 33, "North Building Technologies Limited" },
            { 34, "Notifier" },
            { 35, "Reliable Controls Corporation" },
            { 36, "Tridium Inc." },
            { 37, "Sierra Monitor Corporation/FieldServer Technologies" },
            { 38, "Silicon Energy" },
            { 39, "Kieback & Peter GmbH & Co KG" },
            { 40, "Anacon Systems, Inc." },
            { 41, "Systems Controls & Instruments, LLC" },
            { 42, "Acuity Brands Lighting, Inc." },
            { 43, "Micropower Manufacturing" },
            { 44, "Matrix Controls" },
            { 45, "METALAIRE" },
            { 46, "ESS Engineering" },
            { 47, "Sphere Systems Pty Ltd." },
            { 48, "Walker Technologies Corporation" },
            { 49, "H I Solutions, Inc." },
            { 50, "MBS GmbH" },
            { 51, "SAMSON AG" },
            { 52, "Badger Meter Inc." },
            { 53, "DAIKIN Industries Ltd." },
            { 54, "NARA Controls Inc." },
            { 55, "Mammoth Inc." },
            { 56, "Liebert Corporation" },
            { 57, "SEMCO Incorporated" },
            { 58, "Air Monitor Corporation" },
            { 59, "TRIATEK, LLC" },
            { 60, "NexLight" },
            { 61, "Multistack" },
            { 62, "TSI Incorporated" },
            { 63, "Weather-Rite, Inc." },
            { 64, "Dunham-Bush" },
            { 65, "Reliance Electric" },
            { 66, "LCS Inc." },
            { 67, "Regulator Australia PTY Ltd." },
            { 68, "Touch-Plate Lighting Controls" },
            { 69, "Amann GmbH" },
            { 70, "RLE Technologies" },
            { 71, "Cardkey Systems" },
            { 72, "SECOM Co., Ltd." },
            { 73, "ABB Gebaeudetechnik AG Bereich NetServ" },
            { 74, "KNX Association cvba" },
            { 75, "Institute of Electrical Installation Engineers of Japan (IEIEJ)" },
            { 76, "Nohmi Bosai, Ltd." },
            { 77, "Carel S.p.A." },
            { 78, "UTC Fire & Security Espana, S.L." },
            { 79, "Hochiki Corporation" },
            { 80, "Fr. Sauter AG" },
            { 81, "Matsushita Electric Works, Ltd." },
            { 82, "Mitsubishi Electric Corporation, Inazawa Works" },
            { 83, "Mitsubishi Heavy Industries, Ltd." },
            { 84, "Xylem, Inc." },
            { 85, "Yamatake Building Systems Co., Ltd." },
            { 86, "The Watt Stopper, Inc." },
            { 87, "Aichi Tokei Denki Co., Ltd." },
            { 88, "Activation Technologies, LLC" },
            { 89, "Saia-Burgess Controls, Ltd." },
            { 90, "Hitachi, Ltd." },
            { 91, "Novar Corp./Trend Control Systems Ltd." },
            { 92, "Mitsubishi Electric Lighting Corporation" },
            { 93, "Argus Control Systems, Ltd." },
            { 94, "Kyuki Corporation" },
            { 95, "Richards-Zeta Building Intelligence, Inc." },
            { 96, "Scientech R&D, Inc." },
            { 97, "VCI Controls, Inc." },
            { 98, "Toshiba Corporation" },
            { 99, "Mitsubishi Electric Corporation Air Conditioning & Refrigeration Systems Works" },
            { 100, "Custom Mechanical Equipment, LLC" },
            { 101, "ClimateMaster" },
            { 102, "ICP Panel-Tec, Inc." },
            { 103, "D-Tek Controls" },
            { 104, "NEC Engineering, Ltd." },
            { 105, "PRIVA BV" },
            { 106, "Meidensha Corporation" },
            { 107, "JCI Systems Integration Services" },
            { 108, "Freedom Corporation" },
            { 109, "Neuberger Gebaeudeautomation GmbH" },
            { 110, "eZi Controls" },
            { 111, "Leviton Manufacturing" },
            { 112, "Fujitsu Limited" },
            { 113, "Emerson Network Power" },
            { 114, "S. A. Armstrong, Ltd." },
            { 115, "Visonet AG" },
            { 116, "M&M Systems, Inc." },
            { 117, "Custom Software Engineering" },
            { 118, "Nittan Company, Limited" },
            { 119, "Elutions Inc. (Wizcon Systems SAS)" },
            { 120, "Pacom Systems Pty., Ltd." },
            { 121, "Unico, Inc." },
            { 122, "Ebtron, Inc." },
            { 123, "Scada Engine" },
            { 124, "AC Technology Corporation" },
            { 125, "Eagle Technology" },
            { 126, "Data Aire, Inc." },
            { 127, "ABB, Inc." },
            { 128, "Transbit Sp. z o. o." },
            { 129, "Toshiba Carrier Corporation" },
            { 130, "Shenzhen Junzhi Hi-Tech Co., Ltd." },
            { 131, "Tokai Soft" },
            { 132, "Blue Ridge Technologies" },
            { 133, "Veris Industries" },
            { 134, "Centaurus Prime" },
            { 135, "Sand Network Systems" },
            { 136, "Regulvar, Inc." },
            { 137, "AFDtek Division of Fastek International Inc." },
            { 138, "PowerCold Comfort Air Solutions, Inc." },
            { 139, "I Controls" },
            { 140, "Viconics Electronics, Inc." },
            { 141, "Yaskawa America, Inc." },
            { 142, "DEOS control systems GmbH" },
            { 143, "Digitale Mess- und Steuersysteme AG" },
            { 144, "Fujitsu General Limited" },
            { 145, "Project Engineering S.r.l." },
            { 146, "Sanyo Electric Co., Ltd." },
            { 147, "Integrated Information Systems, Inc." },
            { 148, "Temco Controls, Ltd." },
            { 149, "Airtek International Inc." },
            { 150, "Advantech Corporation" },
            { 151, "Titan Products, Ltd." },
            { 152, "Regel Partners" },
            { 153, "National Environmental Product" },
            { 154, "Unitec Corporation" },
            { 155, "Kanden Engineering Company" },
            { 156, "Messner Gebaeudetechnik GmbH" },
            { 157, "Integrated.CH" },
            { 158, "Price Industries" },
            { 159, "SE-Elektronic GmbH" },
            { 160, "Rockwell Automation" },
            { 161, "Enflex Corp." },
            { 162, "ASI Controls" },
            { 163, "SysMik GmbH Dresden" },
            { 164, "HSC Regelungstechnik GmbH" },
            { 165, "Smart Temp Australia Pty.  Ltd." },
            { 166, "Cooper Controls" },
            { 167, "Duksan Mecasys Co., Ltd." },
            { 168, "Fuji IT Co., Ltd." },
            { 169, "Vacon Plc" },
            { 170, "Leader Controls" },
            { 171, "Cylon Controls, Ltd." },
            { 172, "Compas" },
            { 173, "Mitsubishi Electric Building Techno-Service Co., Ltd." },
            { 174, "Building Control Integrators" },
            { 175, "ITG Worldwide (M) Sdn Bhd" },
            { 176, "Lutron Electronics Co., Inc." },
            { 177, "Cooper-Atkins Corporation" },
            { 178, "LOYTEC Electronics GmbH" },
            { 179, "ProLon" },
            { 180, "Mega Controls Limited" },
            { 181, "Micro Control Systems, Inc." },
            { 182, "Kiyon, Inc." },
            { 183, "Dust Networks" },
            { 184, "Advanced Building Automation Systems" },
            { 185, "Hermos AG" },
            { 186, "CEZIM" },
            { 187, "Softing" },
            { 188, "Lynxspring, Inc." },
            { 189, "Schneider Toshiba Inverter Europe" },
            { 190, "Danfoss Drives A/S" },
            { 191, "Eaton Corporation" },
            { 192, "Matyca S.A." },
            { 193, "Botech AB" },
            { 194, "Noveo, Inc." },
            { 195, "AMEV" },
            { 196, "Yokogawa Electric Corporation" },
            { 197, "GFR Gesellschaft fuer Regelungstechnik" },
            { 198, "Exact Logic" },
            { 199, "Mass Electronics Pty Ltd dba Innotech Control Systems Australia" },
            { 200, "Kandenko Co., Ltd." },
            { 201, "DTF, Daten-Technik Fries" },
            { 202, "Klimasoft, Ltd." },
            { 203, "Toshiba Schneider Inverter Corporation" },
            { 204, "Control Applications, Ltd." },
            { 205, "KDT Systems Co., Ltd." },
            { 206, "Onicon Incorporated" },
            { 207, "Automation Displays, Inc." },
            { 208, "Control Solutions, Inc." },
            { 209, "Remsdaq Limited" },
            { 210, "NTT Facilities, Inc." },
            { 211, "VIPA GmbH" },
            { 212, "TSC21 Association of Japan" },
            { 213, "Strato Automation" },
            { 214, "HRW Limited" },
            { 215, "Lighting Control & Design, Inc." },
            { 216, "Mercy Electronic and Electrical Industries" },
            { 217, "Samsung SDS Co., Ltd" },
            { 218, "Impact Facility Solutions, Inc." },
            { 219, "Aircuity" },
            { 220, "Control Techniques, Ltd." },
            { 221, "OpenGeneral Pty., Ltd." },
            { 222, "WAGO Kontakttechnik GmbH & Co. KG" },
            { 223, "Cerus Industrial" },
            { 224, "Chloride Power Protection Company" },
            { 225, "Computrols, Inc." },
            { 226, "Phoenix Contact GmbH & Co. KG" },
            { 227, "Grundfos Management A/S" },
            { 228, "Ridder Drive Systems" },
            { 229, "Soft Device SDN BHD" },
            { 230, "Integrated Control Technology Limited" },
            { 231, "AIRxpert Systems, Inc." },
            { 232, "Microtrol Limited" },
            { 233, "Red Lion Controls" },
            { 234, "Digital Electronics Corporation" },
            { 235, "Ennovatis GmbH" },
            { 236, "Serotonin Software Technologies, Inc." },
            { 237, "LS Industrial Systems Co., Ltd." },
            { 238, "Square D Company" },
            { 239, "S Squared Innovations, Inc." },
            { 240, "Aricent Ltd." },
            { 241, "EtherMetrics, LLC" },
            { 242, "Industrial Control Communications, Inc." },
            { 243, "Paragon Controls, Inc." },
            { 244, "A. O. Smith Corporation" },
            { 245, "Contemporary Control Systems, Inc." },
            { 246, "Intesis Software SL" },
            { 247, "Ingenieurgesellschaft N. Hartleb mbH" },
            { 248, "Heat-Timer Corporation" },
            { 249, "Ingrasys Technology, Inc." },
            { 250, "Costerm Building Automation" },
            { 251, "WILO SE" },
            { 252, "Embedia Technologies Corp." },
            { 253, "Technilog" },
            { 254, "HR Controls Ltd. & Co. KG" },
            { 255, "Lennox International, Inc." },
            { 256, "RK-Tec Rauchklappen-Steuerungssysteme GmbH & Co. KG" },
            { 257, "Thermomax, Ltd." },
            { 258, "ELCON Electronic Control, Ltd." },
            { 259, "Larmia Control AB" },
            { 260, "BACnet Stack at SourceForge" },
            { 261, "G4S Security Services A/S" },
            { 262, "Exor International S.p.A." },
            { 263, "Cristal Controles" },
            { 264, "Regin AB" },
            { 265, "Dimension Software, Inc." },
            { 266, "SynapSense Corporation" },
            { 267, "Beijing Nantree Electronic Co., Ltd." },
            { 268, "Camus Hydronics Ltd." },
            { 269, "Kawasaki Heavy Industries, Ltd." },
            { 270, "Critical Environment Technologies" },
            { 271, "ILSHIN IBS Co., Ltd." },
            { 272, "ELESTA Energy Control AG" },
            { 273, "KROPMAN Installatietechniek" },
            { 274, "Baldor Electric Company" },
            { 275, "INGA mbH" },
            { 276, "GE Consumer & Industrial" },
            { 277, "Functional Devices, Inc." },
            { 278, "ESAC" },
            { 279, "M-System Co., Ltd." },
            { 280, "Yokota Co., Ltd." },
            { 281, "Hitranse Technology Co., LTD" },
            { 282, "Vigilent Corporation" },
            { 283, "Kele, Inc." },
            { 284, "Opera Electronics, Inc." },
            { 285, "Gentec" },
            { 286, "Embedded Science Labs, LLC" },
            { 287, "Parker Hannifin Corporation" },
            { 288, "MaCaPS International Limited" },
            { 289, "Link4 Corporation" },
            { 290, "Romutec Steuer-u. Regelsysteme GmbH" },
            { 291, "Pribusin, Inc." },
            { 292, "Advantage Controls" },
            { 293, "Critical Room Control" },
            { 294, "LEGRAND" },
            { 295, "Tongdy Control Technology Co., Ltd." },
            { 296, "ISSARO Integrierte Systemtechnik" },
            { 297, "Pro-Dev Industries" },
            { 298, "DRI-STEEM" },
            { 299, "Creative Electronic GmbH" },
            { 300, "Swegon AB" },
            { 301, "Jan Brachacek" },
            { 302, "Hitachi Appliances, Inc." },
            { 303, "Real Time Automation, Inc." },
            { 304, "ITEC Hankyu-Hanshin Co." },
            { 305, "Cyrus E&M Engineering Co., Ltd." },
            { 306, "Badger Meter" },
            { 307, "Cirrascale Corporation" },
            { 308, "Elesta GmbH Building Automation" },
            { 309, "Securiton" },
            { 310, "OSlsoft, Inc." },
            { 311, "Hanazeder Electronic GmbH" },
            { 312, "Honeywell Security Deutschland, Novar GmbH" },
            { 313, "Siemens Industry, Inc." },
            { 314, "ETM Professional Control GmbH" },
            { 315, "Meitav-tec, Ltd." },
            { 316, "Janitza Electronics GmbH" },
            { 317, "MKS Nordhausen" },
            { 318, "De Gier Drive Systems B.V." },
            { 319, "Cypress Envirosystems" },
            { 320, "SMARTron s.r.o." },
            { 321, "Verari Systems, Inc." },
            { 322, "K-W Electronic Service, Inc." },
            { 323, "ALFA-SMART Energy Management" },
            { 324, "Telkonet, Inc." },
            { 325, "Securiton GmbH" },
            { 326, "Cemtrex, Inc." },
            { 327, "Performance Technologies, Inc." },
            { 328, "Xtralis (Aust) Pty Ltd" },
            { 329, "TROX GmbH" },
            { 330, "Beijing Hysine Technology Co., Ltd" },
            { 331, "RCK Controls, Inc." },
            { 332, "Distech Controls SAS" },
            { 333, "Novar/Honeywell" },
            { 334, "The S4 Group, Inc." },
            { 335, "Schneider Electric" },
            { 336, "LHA Systems" },
            { 337, "GHM engineering Group, Inc." },
            { 338, "Cllimalux S.A." },
            { 339, "VAISALA Oyj" },
            { 340, "COMPLEX (Beijing) Technology, Co., LTD." },
            { 341, "SCADAmetrics" },
            { 342, "POWERPEG NSI Limited" },
            { 343, "BACnet Interoperability Testing Services, Inc." },
            { 344, "Teco a.s." },
            { 345, "Plexus Technology, Inc." },
            { 346, "Energy Focus, Inc." },
            { 347, "Powersmiths International Corp." },
            { 348, "Nichibei Co., Ltd." },
            { 349, "HKC Technology Ltd." },
            { 350, "Ovation Networks, Inc." },
            { 351, "Setra Systems" },
            { 352, "AVG Automation" },
            { 353, "ZXC Ltd." },
            { 354, "Byte Sphere" },
            { 355, "Generiton Co., Ltd." },
            { 356, "Holter Regelarmaturen GmbH & Co. KG" },
            { 357, "Bedford Instruments, LLC" },
            { 358, "Standair Inc." },
            { 359, "WEG Automation - R&D" },
            { 360, "Prolon Control Systems ApS" },
            { 361, "Inneasoft" },
            { 362, "ConneXSoft GmbH" },
            { 363, "CEAG Notlichtsysteme GmbH" },
            { 364, "Distech Controls Inc." },
            { 365, "Industrial Technology Research Institute" },
            { 366, "ICONICS, Inc." },
            { 367, "IQ Controls s.c." },
            { 368, "OJ Electronics A/S" },
            { 369, "Rolbit Ltd." },
            { 370, "Synapsys Solutions Ltd." },
            { 371, "ACME Engineering Prod. Ltd." },
            { 372, "Zener Electric Pty, Ltd." },
            { 373, "Selectronix, Inc." },
            { 374, "Gorbet & Banerjee, LLC." },
            { 375, "IME" },
            { 376, "Stephen H. Dawson Computer Service" },
            { 377, "Accutrol, LLC" },
            { 378, "Schneider Elektronik GmbH" },
            { 379, "Alpha-Inno Tec GmbH" },
            { 380, "ADMMicro, Inc." },
            { 381, "Greystone Energy Systems, Inc." },
            { 382, "CAP Technologie" },
            { 383, "KeRo Systems" },
            { 384, "Domat Control System s.r.o." },
            { 385, "Efektronics Pty. Ltd." },
            { 386, "Hekatron Vertriebs GmbH" },
            { 387, "Securiton AG" },
            { 388, "Carlo Gavazzi Controls SpA" },
            { 389, "Chipkin Automation Systems" },
            { 390, "Savant Systems, LLC" },
            { 391, "Simmtronic Lighting Controls" },
            { 392, "Abelko Innovation AB" },
            { 393, "Seresco Technologies Inc." },
            { 394, "IT Watchdogs" },
            { 395, "Automation Assist Japan Corp." },
            { 396, "Thermokon Sensortechnik GmbH" },
            { 397, "EGauge Systems, LLC" },
            { 398, "Quantum Automation (ASIA) PTE, Ltd." },
            { 399, "Toshiba Lighting & Technology Corp." },
            { 400, "SPIN Engenharia de Automacao Ltda." },
            { 401, "Logistics Systems & Software Services India PVT. Ltd." },
            { 402, "Delta Controls Integration Products" },
            { 403, "Focus Media" },
            { 404, "LUMEnergi Inc." },
            { 405, "Kara Systems" },
            { 406, "RF Code, Inc." },
            { 407, "Fatek Automation Corp." },
            { 408, "JANDA Software Company, LLC" },
            { 409, "Open System Solutions Limited" },
            { 410, "Intelec Systems PTY Ltd." },
            { 411, "Ecolodgix, LLC" },
            { 412, "Douglas Lighting Controls" },
            { 413, "iSAtech GmbH" },
            { 414, "AREAL" },
            { 415, "Beckhoff Automation GmbH" },
            { 416, "IPAS GmbH" },
            { 417, "KE2 Therm Solutions" },
            { 418, "Base2Products" },
            { 419, "DTL Controls, LLC" },
            { 420, "INNCOM International, Inc." },
            { 421, "BTR Netcom GmbH" },
            { 422, "Greentrol Automation, Inc" },
            { 423, "BELIMO Automation AG" },
            { 424, "Samsung Heavy Industries Co, Ltd" },
            { 425, "Triacta Power Technologies, Inc." },
            { 426, "Globestar Systems" },
            { 427, "MLB Advanced Media, LP" },
            { 428, "SWG Stuckmann Wirtschaftliche Gebaeudesysteme GmbH" },
            { 429, "SensorSwitch" },
            { 430, "Multitek Power Limited" },
            { 431, "Aquametro AG" },
            { 432, "LG Electronics Inc." },
            { 433, "Electronic Theatre Controls, Inc." },
            { 434, "Mitsubishi Electric Corporation Nagoya Works" },
            { 435, "Delta Electronics, Inc." },
            { 436, "Elma Kurtalj, Ltd." },
            { 437, "ADT Fire and Security Sp. A.o.o." },
            { 438, "Nedap Security Management" },
            { 439, "ESC Automation Inc." },
            { 440, "DSP4YOU Ltd." },
            { 441, "GE Sensing and Inspection Technologies" },
            { 442, "Embedded Systems SIA" },
            { 443, "BEFEGA GmbH" },
            { 444, "Baseline Inc." },
            { 445, "M2M Systems Integrators" },
            { 446, "OEMCtrl" },
            { 447, "Clarkson Controls Limited" },
            { 448, "Rogerwell Control System Limited" },
            { 449, "SCL Elements" },
            { 450, "Hitachi Ltd." },
            { 451, "Newron System SA" },
            { 452, "BEVECO Gebouwautomatisering BV" },
            { 453, "Streamside Solutions" },
            { 454, "Yellowstone Soft" },
            { 455, "Oztech Intelligent Systems Pty Ltd." },
            { 456, "Novelan GmbH" },
            { 457, "Flexim Americas Corporation" },
            { 458, "ICP DAS Co., Ltd." },
            { 459, "CARMA Industries Inc." },
            { 460, "Log-One Ltd." },
            { 461, "TECO Electric & Machinery Co., Ltd." },
            { 462, "ConnectEx, Inc." },
            { 463, "Turbo DDC Suedwest" },
            { 464, "Quatrosense Environmental Ltd." },
            { 465, "Fifth Light Technology Ltd." },
            { 466, "Scientific Solutions, Ltd." },
            { 467, "Controller Area Network Solutions (M) Sdn Bhd" },
            { 468, "RESOL - Elektronische Regelungen GmbH" },
            { 469, "RPBUS LLC" },
            { 470, "BRS Sistemas Eletronicos" },
            { 471, "WindowMaster A/S" },
            { 472, "Sunlux Technologies Ltd." },
            { 473, "Measurlogic" },
            { 474, "Frimat GmbH" },
            { 475, "Spirax Sarco" },
            { 476, "Luxtron" },
            { 477, "Raypak Inc" },
            { 478, "Air Monitor Corporation" },
            { 479, "Regler Och Webbteknik Sverige (ROWS)" },
            { 480, "Intelligent Lighting Controls Inc." },
            { 481, "Sanyo Electric Industry Co., Ltd" },
            { 482, "E-Mon Energy Monitoring Products" },
            { 483, "Digital Control Systems" },
            { 484, "ATI Airtest Technologies, Inc." },
            { 485, "SCS SA" },
            { 486, "HMS Industrial Networks AB" },
            { 487, "Shenzhen Universal Intellisys Co Ltd" },
            { 488, "EK Intellisys Sdn Bhd" },
            { 489, "SysCom" },
            { 490, "Firecom, Inc." },
            { 491, "ESA Elektroschaltanlagen Grimma GmbH" },
            { 492, "Kumahira Co Ltd" },
            { 493, "Hotraco" },
            { 494, "SABO Elektronik GmbH" },
            { 495, "Equip'Trans" },
            { 496, "TCS Basys Controls" },
            { 497, "FlowCon International A/S" },
            { 498, "ThyssenKrupp Elevator Americas" },
            { 499, "Abatement Technologies" },
            { 500, "Continental Control Systems, LLC" },
            { 501, "WISAG Automatisierungstechnik GmbH & Co KG" },
            { 502, "EasyIO" },
            { 503, "EAP-Electric GmbH" },
            { 504, "Hardmeier" },
            { 505, "Mircom Group of Companies" },
            { 506, "Quest Controls" },
            { 507, "Mestek, Inc" },
            { 508, "Pulse Energy" },
            { 509, "Tachikawa Corporation" },
            { 510, "University of Nebraska-Lincoln" },
            { 511, "Redwood Systems" },
            { 512, "PASStec Industrie-Elektronik GmbH" },
            { 513, "NgEK, Inc." },
            { 514, "t-mac Technologies" },
            { 515, "Jireh Energy Tech Co., Ltd." },
            { 516, "Enlighted Inc." },
            { 517, "El-Piast Sp. Z o.o" },
            { 518, "NetxAutomation Software GmbH" },
            { 519, "Invertek Drives" },
            { 520, "Deutschmann Automation GmbH & Co. KG" },
            { 521, "EMU Electronic AG" },
            { 522, "Phaedrus Limited" },
            { 523, "Sigmatek GmbH & Co KG" },
            { 524, "Marlin Controls" },
            { 525, "Circutor, SA" },
            { 526, "UTC Fire & Security" },
            { 527, "DENT Instruments, Inc." },
            { 528, "FHP Manufacturing Company - Bosch Group" },
            { 529, "GE Intelligent Platforms" },
            { 530, "Inner Range Pty Ltd" },
            { 531, "GLAS Energy Technology" },
            { 532, "MSR-Electronic-GmbH" },
            { 533, "Energy Control Systems, Inc." },
            { 534, "EMT Controls" },
            { 535, "Daintree Networks Inc." },
            { 536, "EURO ICC d.o.o" },
            { 537, "TE Connectivity Energy" },
            { 538, "GEZE GmbH" },
            { 539, "NEC Corporation" },
            { 540, "Ho Cheung International Company Limited" },
            { 541, "Sharp Manufacturing Systems Corporation" },
            { 542, "DOT CONTROLS a.s." },
            { 543, "BeaconMedaes" },
            { 544, "Midea Commercial Aircon" },
            { 545, "WattMaster Controls" },
            { 546, "Kamstrup A/S" },
            { 547, "CA Computer Automation GmbH" },
            { 548, "Laars Heating Systems Company" },
            { 549, "Hitachi Systems, Ltd." },
            { 550, "Fushan AKE Electronic Engineering Co., Ltd." },
            { 551, "Toshiba International Corporation" },
            { 552, "Starman Systems, LLC" },
            { 553, "Samsung Techwin Co., Ltd." },
            { 554, "ISAS-Integrated Switchgear and Systems P/L" },
            { 555, "reserved by ASHRAE" },
            { 556, "Obvius" },
            { 557, "Marek Guzik" },
            { 558, "Vortek Instruments, LLC" },
            { 559, "Universal Lighting Technologies" },
            { 560, "Myers Power Products, Inc." },
            { 561, "Vector Controls GmbH" },
            { 562, "Crestron Electronics, Inc." },
            { 563, "A&E Controls Limited" },
            { 564, "Projektomontaza A.D." },
            { 565, "Freeaire Refrigeration" },
            { 566, "Aqua Cooler Pty Limited" },
            { 567, "Basic Controls" },
            { 568, "GE Measurement and Control Solutions Advanced Sensors" },
            { 569, "EQUAL Networks" },
            { 570, "Millennial Net" },
            { 571, "APLI Ltd" },
            { 572, "Electro Industries/GaugeTech" },
            { 573, "SangMyung University" },
            { 574, "Coppertree Analytics, Inc." },
            { 575, "CoreNetiX GmbH" },
            { 576, "Acutherm" },
            { 577, "Dr. Riedel Automatisierungstechnik GmbH" },
            { 578, "Shina System Co., Ltd" },
            { 579, "Iqapertus" },
            { 580, "PSE Technology" },
            { 581, "BA Systems" },
            { 582, "BTICINO" },
            { 583, "Monico, Inc." },
            { 584, "iCue" },
            { 585, "tekmar Control Systems Ltd." },
            { 586, "Control Technology Corporation" },
            { 587, "GFAE GmbH" },
            { 588, "BeKa Software GmbH" },
            { 589, "Isoil Industria SpA" },
            { 590, "Home Systems Consulting SpA" },
            { 591, "Socomec" },
            { 592, "Everex Communications, Inc." },
            { 593, "Ceiec Electric Technology" },
            { 594, "Atrila GmbH" },
            { 595, "WingTechs" },
            { 596, "Shenzhen Mek Intellisys Pte Ltd." },
            { 597, "Nestfield Co., Ltd." },
            { 598, "Swissphone Telecom AG" },
            { 599, "PNTECH JSC" },
            { 600, "Horner APG, LLC" },
            { 601, "PVI Industries, LLC" },
            { 602, "Ela-compil" },
            { 603, "Pegasus Automation International LLC" },
            { 604, "Wight Electronic Services Ltd." },
            { 605, "Marcom" },
            { 606, "Exhausto A/S" },
            { 607, "Dwyer Instruments, Inc." },
            { 608, "Link GmbH" },
            { 609, "Oppermann Regelgerate GmbH" },
            { 610, "NuAire, Inc." },
            { 611, "Nortec Humidity, Inc." },
            { 612, "Bigwood Systems, Inc." },
            { 613, "Enbala Power Networks" },
            { 614, "Inter Energy Co., Ltd." },
            { 615, "ETC" },
            { 616, "COMELEC S.A.R.L" },
            { 617, "Pythia Technologies" },
            { 618, "TrendPoint Systems, Inc." },
            { 619, "AWEX" },
            { 620, "Eurevia" },
            { 621, "Kongsberg E-lon AS" },
            { 622, "FlaktWoods" },
            { 623, "E + E Elektronik GES M.B.H." },
            { 624, "ARC Informatique" },
            { 625, "SKIDATA AG" },
            { 626, "WSW Solutions" },
            { 627, "Trefon Electronic GmbH" },
            { 628, "Dongseo System" },
            { 629, "Kanontec Intelligence Technology Co., Ltd." },
            { 630, "EVCO S.p.A." },
            { 631, "Accuenergy (CANADA) Inc." },
            { 632, "SoftDEL" },
            { 633, "Orion Energy Systems, Inc." },
            { 634, "Roboticsware" },
            { 635, "DOMIQ Sp. z o.o." },
            { 636, "Solidyne" },
            { 637, "Elecsys Corporation" },
            { 638, "Conditionaire International Pty. Limited" },
            { 639, "Quebec, Inc." },
            { 640, "Homerun Holdings" },
            { 641, "Murata Americas" },
            { 642, "Comptek" },
            { 643, "Westco Systems, Inc." },
            { 644, "Advancis Software & Services GmbH" },
            { 645, "Intergrid, LLC" },
            { 646, "Markerr Controls, Inc." },
            { 647, "Toshiba Elevator and Building Systems Corporation" },
            { 648, "Spectrum Controls, Inc." },
            { 649, "Mkservice" },
            { 650, "Fox Thermal Instruments" },
            { 651, "SyxthSense Ltd" },
            { 652, "DUHA System S R.O." },
            { 653, "NIBE" },
            { 654, "Melink Corporation" },
            { 655, "Fritz-Haber-Institut" },
            { 656, "MTU Onsite Energy GmbH, Gas Power Systems" },
            { 657, "Omega Engineering, Inc." },
            { 658, "Avelon" },
            { 659, "Ywire Technologies, Inc." },
            { 660, "M.R. Engineering Co., Ltd." },
            { 661, "Lochinvar, LLC" },
            { 662, "Sontay Limited" },
            { 663, "GRUPA Slawomir Chelminski" },
            { 664, "Arch Meter Corporation" },
            { 665, "Senva, Inc." },
            { 666, "reserved by ASHRAE" },
            { 667, "FM-Tec" },
            { 668, "Systems Specialists, Inc." },
            { 669, "SenseAir" },
            { 670, "AB IndustrieTechnik Srl" },
            { 671, "Cortland Research, LLC" },
            { 672, "MediaView" },
            { 673, "VDA Elettronica" },
            { 674, "CSS, Inc." },
            { 675, "Tek-Air Systems, Inc." },
            { 676, "ICDT" },
            { 677, "The Armstrong Monitoring Corporation" },
            { 678, "DIXELL S.r.l" },
            { 679, "Lead System, Inc." },
            { 680, "ISM EuroCenter S.A." },
            { 681, "TDIS" },
            { 682, "Trade FIDES" },
            { 683, "Knuerr GmbH (Emerson Network Power)" },
            { 684, "Resource Data Management" },
            { 685, "Abies Technology, Inc." },
            { 686, "Amalva" },
            { 687, "MIRAE Electrical Mfg. Co., Ltd." },
            { 688, "HunterDouglas Architectural Projects Scandinavia ApS" },
            { 689, "RUNPAQ Group Co., Ltd" },
            { 690, "Unicard SA" },
            { 691, "IE Technologies" },
            { 692, "Ruskin Manufacturing" },
            { 693, "Calon Associates Limited" },
            { 694, "Contec Co., Ltd." },
            { 695, "iT GmbH" },
            { 696, "Autani Corporation" },
            { 697, "Christian Fortin" },
            { 698, "HDL" },
            { 699, "IPID Sp. Z.O.O Limited" },
            { 700, "Fuji Electric Co., Ltd" },
            { 701, "View, Inc." },
            { 702, "Samsung S1 Corporation" },
            { 703, "New Lift" },
            { 704, "VRT Systems" },
            { 705, "Motion Control Engineering, Inc." },
            { 706, "Weiss Klimatechnik GmbH" },
            { 707, "Elkon" },
            { 708, "Eliwell Controls S.r.l." },
            { 709, "Japan Computer Technos Corp" },
            { 710, "Rational Network ehf" },
            { 711, "Magnum Energy Solutions, LLC" },
            { 712, "MelRok" },
            { 713, "VAE Group" },
            { 714, "LGCNS" },
            { 715, "Berghof Automationstechnik GmbH" },
            { 716, "Quark Communications, Inc." },
            { 717, "Sontex" },
            { 718, "mivune AG" },
            { 719, "Panduit" },
            { 720, "Smart Controls, LLC" },
            { 721, "Compu-Aire, Inc." },
            { 722, "Sierra" },
            { 723, "ProtoSense Technologies" },
            { 724, "Eltrac Technologies Pvt Ltd" },
            { 725, "Bektas Invisible Controls GmbH" },
            { 726, "Entelec" },
            { 727, "INNEXIV" },
            { 728, "Covenant" },
            { 729, "Davitor AB" },
            { 730, "TongFang Technovator" },
            { 731, "Building Robotics, Inc." },
            { 732, "HSS-MSR UG" },
            { 733, "FramTack LLC" },
            { 734, "B. L. Acoustics, Ltd." },
            { 735, "Traxxon Rock Drills, Ltd" },
            { 736, "Franke" },
            { 737, "Wurm GmbH & Co" },
            { 738, "AddENERGIE" },
            { 739, "Mirle Automation Corporation" },
            { 740, "Ibis Networks" },
            { 741, "ID-KARTA s.r.o." },
            { 742, "Anaren, Inc." },
            { 743, "Span, Incorporated" },
            { 744, "Bosch Thermotechnology Corp" },
            { 745, "DRC Technology S.A." },
            { 746, "Shanghai Energy Building Technology Co, Ltd" },
            { 747, "Fraport AG" },
            { 748, "Flowgroup" },
            { 749, "Skytron Energy, GmbH" },
            { 750, "ALTEL Wicha, Golda Sp. J." },
            { 751, "Drupal" },
            { 752, "Axiomatic Technology, Ltd" },
            { 753, "Bohnke + Partner" },
            { 754, "Function 1" },
            { 755, "Optergy Pty, Ltd" },
            { 756, "LSI Virticus" },
            { 757, "Konzeptpark GmbH" },
            { 758, "Hubbell Building Automation, Inc." },
            { 759, "eCurv, Inc." },
            { 760, "Agnosys GmbH" },
            { 761, "Shanghai Sunfull Automation Co., LTD" },
            { 762, "Kurz Instruments, Inc." },
            { 763, "Cias Elettronica S.r.l." },
            { 764, "Multiaqua, Inc." },
            { 765, "BlueBox" },
            { 766, "Sensidyne" },
            { 767, "Viessmann Elektronik GmbH" },
            { 768, "ADFweb.com srl" },
            { 769, "Gaylord Industries" },
            { 770, "Majur Ltd." },
            { 771, "Shanghai Huilin Technology Co., Ltd." },
            { 772, "Exotronic" },
            { 773, "Safecontrol spol s.r.o." },
            { 774, "Amatis" },
            { 775, "Universal Electric Corporation" },
            { 776, "iBACnet" },
            { 777, "reserved by ASHRAE" },
            { 778, "Smartrise Engineering, Inc." },
            { 779, "Miratron, Inc." },
            { 780, "SmartEdge" },
            { 781, "Mitsubishi Electric Australia Pty Ltd" },
            { 782, "Triangle Research International Ptd Ltd" },
            { 783, "Produal Oy" },
            { 784, "Milestone Systems A/S" },
            { 785, "Trustbridge" },
            { 786, "Feedback Solutions" },
            { 787, "IES" },
            { 788, "GE Critical Power" },
            { 789, "Riptide IO" },
            { 790, "Messerschmitt Systems AG" },
            { 791, "Dezem Energy Controlling" },
            { 792, "MechoSystems" },
            { 793, "evon GmbH" },
            { 794, "CS Lab GmbH" },
            { 795, "8760 Enterprises, Inc." },
            { 796, "Touche Controls" },
            { 797, "Ontrol Teknik Malzeme San. ve Tic. A.S." },
            { 798, "Uni Control System Sp. Z o.o." },
            { 799, "Weihai Ploumeter Co., Ltd" },
            { 800, "Elcom International Pvt. Ltd" },
            { 801, "Philips Lighting" },
            { 802, "AutomationDirect" },
            { 803, "Paragon Robotics" },
            { 804, "SMT System & Modules Technology AG" },
            { 805, "OS Technology Service and Trading Co., LTD" },
            { 806, "CMR Controls Ltd" },
            { 807, "Innovari, Inc." },
            { 808, "ABB Control Products" },
            { 809, "Gesellschaft fur Gebaeudeautomation mbH" },
            { 810, "RODI Systems Corp." },
            { 811, "Nextek Power Systems" },
            { 812, "Creative Lighting" },
            { 813, "WaterFurnace International" },
            { 814, "Mercury Security" },
            { 815, "Hisense (Shandong) Air-Conditioning Co., Ltd." },
            { 816, "Layered Solutions, Inc." },
            { 817, "Leegood Automatic System, Inc." },
            { 818, "Shanghai Restar Technology Co., Ltd." },
            { 819, "Reimann Ingenieurbuero" },
            { 820, "LynTec" },
            { 821, "HTP" },
            { 822, "Elkor Technologies, Inc." },
            { 823, "Bentrol Pty Ltd" },
            { 824, "Team-Control Oy" },
            { 825, "NextDevice, LLC" },
            { 826, "GLOBAL CONTROL 5 Sp. z o.o." },
            { 827, "King I Electronics Co., Ltd" },
            { 828, "SAMDAV" },
            { 829, "Next Gen Industries Pvt. Ltd." },
            { 830, "Entic LLC" },
            { 831, "ETAP" },
            { 832, "Moralle Electronics Limited" },
            { 833, "Leicom AG" },
            { 834, "Watts Regulator Company" },
            { 835, "S.C. Orbtronics S.R.L." },
            { 836, "Gaussan Technologies" },
            { 837, "WEBfactory GmbH" },
            { 838, "Ocean Controls" },
            { 839, "Messana  Air-Ray Conditioning s.r.l." },
            { 840, "Hangzhou BATOWN Technology Co. Ltd." },
            { 841, "Reasonable Controls" },
            { 842, "Servisys, Inc." },
            { 843, "halstrup-walcher GmbH" },
            { 844, "SWG Automation Fuzhou Limited" },
            { 845, "KSB Aktiengesellschaft" },
            { 846, "Hybryd Sp. z o.o." },
            { 847, "Helvatron AG" },
            { 848, "Oderon Sp. Z.O.O." },
            { 849, "miko" },
            { 850, "Exodraft" },
            { 851, "Hochhuth GmbH" },
            { 852, "Integrated System Technologies Ltd." },
            { 853, "Shanghai Cellcons Controls Co., Ltd" },
            { 854, "Emme Controls, LLC" },
            { 855, "Field Diagnostic Services, Inc." },
            { 856, "Ges Teknik A.S." },
            { 857, "Global Power Products, Inc." },
            { 858, "Option NV" },
            { 859, "BV-Control AG" },
            { 860, "Sigren Engineering AG" },
            { 861, "Shanghai Jaltone Technology Co., Ltd." },
            { 862, "MaxLine Solutions Ltd" },
            { 863, "Kron Instrumentos Eletricos Ltda" },
            { 864, "Thermo Matrix" },
            { 865, "Infinite Automation Systems, Inc." },
            { 866, "Vantage" },
            { 867, "Elecon Measurements Pvt Ltd" },
            { 868, "TBA" },
            { 869, "Carnes Company" },
            { 870, "Harman Professional" },
            { 871, "Nenutec Asia Pacific Pte Ltd" },
            { 872, "Gia NV" },
            { 873, "Kepware Tehnologies" },
            { 874, "Temperature Electronics Ltd" },
            { 875, "Packet Power" },
            { 876, "Project Haystack Corporation" },
            { 877, "DEOS Controls Americas Inc." },
            { 878, "Senseware Inc" },
            { 879, "MST Systemtechnik AG" },
            { 880, "Lonix Ltd" },
            { 881, "GMC-I Messtechnik GmbH" },
            { 882, "Aviosys International Inc." },
            { 883, "Efficient Building Automation Corp." },
            { 884, "Accutron Instruments Inc." },
            { 885, "Vermont Energy Control Systems LLC" },
            { 886, "DCC Dynamics" },
            { 887, "Brueck Electronic GmbH" },
            { 888, "reserved by ASHRAE" },
            { 889, "NGBS Hungary Ltd." },
            { 890, "ILLUM Technology, LLC" },
            { 891, "Delta Controls Germany Limited" },
            { 892, "S+T Service & Technique S.A." },
            { 893, "SimpleSoft" },
            { 894, "Candi Controls, Inc." },
            { 895, "EZEN Solution Inc." },
            { 896, "Fujitec Co. Ltd." },
            { 897, "Terralux" },
            { 898, "Annicom" },
            { 899, "Bihl+Wiedemann GmbH" },
            { 900, "Daper, Inc." },
            { 901, "Schueco International KG" },
            { 902, "Otis Elevator Company" },
            { 903, "Fidelix Oy" },
            { 904, "RAM GmbH Mess- und Regeltechnik" },
            { 905, "WEMS" },
            { 906, "Ravel Electronics Pvt Ltd" },
            { 907, "OmniMagni" },
            { 908, "Echelon" },
            { 909, "Intellimeter Canada, Inc." },
            { 910, "Bithouse Oy" },
            { 912, "BuildPulse" },
            { 913, "Shenzhen 1000 Building Automation Co. Ltd" },
            { 914, "AED Engineering GmbH" },
            { 915, "Guentner GmbH & Co. KG" },
            { 916, "KNXlogic" },
            { 917, "CIM Environmental Group" },
            { 918, "Flow Control" },
            { 919, "Lumen Cache, Inc." },
            { 920, "Ecosystem" },
            { 921, "Potter Electric Signal Company, LLC" },
            { 922, "Tyco Fire & Security S.p.A." },
            { 923, "Watanabe Electric Industry Co., Ltd." },
            { 924, "Causam Energy" },
            { 925, "W-tec AG" },
            { 926, "IMI Hydronic Engineering International SA" },
            { 927, "ARIGO Software" },
            { 928, "MSA Safety" },
            { 929, "Smart Solucoes Ltda - MERCATO" },
            { 930, "PIATRA Engineering" },
            { 931, "ODIN Automation Systems, LLC" },
            { 932, "Belparts NV" },
            { 933, "UAB, SALDA" },
            { 934, "Alre-IT Regeltechnik GmbH" },
            { 935, "Ingenieurbuero H. Lertes GmbH & Co. KG" },
            { 936, "Breathing Buildings" },
            { 937, "eWON SA" },
            { 938, "Cav. Uff. Giacomo Cimberio S.p.A" },
            { 939, "PKE Electronics AG" },
            { 940, "Allen" },
            { 941, "Kastle Systems" },
            { 942, "Logical Electro-Mechanical (EM) Systems, Inc." },
            { 943, "ppKinetics Instruments, LLC" },
            { 944, "Cathexis Technologies" },
            { 945, "Sylop Limited" },
            { 946, "Brauns Control GmbH" },
            { 947, "Omron Corporation" },
            { 948, "Wildeboer Bauteile Gmbh" },
            { 949, "Shanghai Biens Technologies Ltd:" },
            { 950, "Beijing HZHY Technology Co., Ltd;" },
            { 951, "Building Clouds" },
            { 952, "The University of Sheffield-Department of Electronic and Electrical Engineering" },
            { 953, "Fabtronics Australia Pty Ltd" },
            { 954, "SLAT" },
            { 955, "Software Motor Corporation" },
            { 956, "Armstrong International Inc." },
            { 957, "Steril-Aire, Inc." },
            { 958, "Infinique" },
            { 959, "Arcom" },
            { 960, "Argo Performance, Ltd" },
            { 961, "Dialight" },
            { 962, "Ideal Technical Solutions" },
            { 963, "Neurobat AG" },
            { 964, "Neyer Software Consulting LLC" },
            { 965, "SCADA Technology Development Co., Ltd." },
            { 966, "Demand Logic Limited" },
            { 967, "GWA Group Limited" },
            { 968, "Occitaline" },
            { 969, "NAO Digital Co., Ltd." },
            { 970, "Shenzhen Chanslink Network Technology Co., Ltd." },
            { 971, "Samsung Electronics Co., Ltd." },
            { 972, "Mesa Laboratories, Inc." },
            { 973, "Fischer" },
            { 974, "OpSys Solutions Ltd." },
            { 975, "Advanced Devices Limited" },
            { 976, "Condair" },
            { 977, "INELCOM Ingenieria Electronica Comercial S.A." },
            { 978, "GridPoint, Inc." },
            { 979, "ADF Technologies Sdn Bhd" },
            { 980, "EPM, Inc." },
            { 981, "Lighting Controls Ltd." },
            { 982, "Perix Controls Ltd." },
            { 983, "AERCO International, Inc." },
            { 984, "KONE Inc." },
            { 985, "Ziehl - Abegg SE" },
            { 986, "Robot, S.A.Bernat Pons" },
            { 987, "Optigo Networks, Inc." },
            { 988, "Openmotics BVBA" },
            { 989, "Metropolitan Industries, Inc." },
            { 990, "Huawei Technologies Co., Ltd." },
            { 991, "OSRAM Sylvania, Inc." },
            { 992, "Vanti" },
            { 993, "Cree, Inc." },
            { 994, "Richmond Heights SDN BHD" },
            { 995, "Payne - Sparkman Lighting Management" },
            { 996, "Ashcroft" },
            { 997, "Jet Controls Corp" },
            { 998, "Zumtobel Lighting GmbH" },
            { 999, "reserved by ASHRAE" },
            { 1000, "Ekon GmbH" },
            { 1001, "Molex GmbH" },
            { 1002, "Maco Lighting Pty Ltd." },
            { 1003, "Axecon Corp." },
            { 1004, "Tensor plc" },
            { 1005, "Kaseman Environmental Control Equipment(Shanghai) Limited" },
            { 1006, "AB Axis Industries" },
            { 1007, "Netix Controls" },
            { 1008, "Eldridge Products, Inc." },
            { 1009, "Micronics" },
            { 1010, "Fortecho Solutions Ltd." },
            { 1011, "Sellers Manufacturing Company" },
            { 1012, "Rite - Hite Doors, Inc." },
            { 1013, "Violet Defense LLC" },
            { 1014, "Simna" },
            { 1015, "Multi - Energie Best Inc." },
            { 1016, "Mega System Technologies, Inc." },
            { 1017, "Rheem" },
            { 1018, "Ing.Punzenberger COPA - DATA GmbH" },
            { 1019, "MEC Electronics GmbH" },
            { 1020, "Taco Comfort Solutions" },
            { 1021, "Alexander Maier GmbH" },
            { 1022, "Ecorithm, Inc." },
            { 1023, "Accurro Ltd." },
            { 1024, "ROMTECK Australia Pty Ltd." },
            { 1025, "Splash Monitoring Limited" },
            { 1026, "Light Application" },
            { 1027, "Logical Building Automation" },
            { 1028, "Exilight Oy" },
            { 1029, "Hager Electro SAS" },
            { 1030, "KLIF Co. LTD." },
            { 1031, "HygroMatik" },
            { 1032, "Daniel Mousseau Programmation & Electronique" },
            { 1033, "Aerionics Inc." },
            { 1034, "M2S Electronique Ltee" },
            { 1035, "Automation Components, Inc." },
            { 1036, "Niobrara Research & Development Corporation" },
            { 1037, "Netcom Sicherheitstechnik GmbH" },
            { 1038, "Lumel S.A." },
            { 1039, "Great Plains Industries, Inc." },
            { 1040, "Domotica Labs S.R.L" },
            { 1041, "Energy Cloud, Inc." },
            { 1042, "Vomatec" },
            { 1043, "Demma Companies" },
            { 1044, "Valsena" },
            { 1045, "Comsys Buertsch AG" },
            { 1046, "bGrid" },
            { 1047, "MDJ Software Pty Ltd" },
            { 1048, "Dimonoff, Inc." },
            { 1049, "Edomo Systems" },
            { 1050, "Effektiv, LLC" },
            { 1051, "SteamOVap" },
            { 1052, "grandcentrix GmbH" },
            { 1053, "Weintek Labs, Inc." },
            { 1054, "Intefox GmbH" },
            { 1055, "Radius22 Automation Company" },
            { 1056, "Ringdale, Inc." },
            { 1057, "Iwaki America" },
            { 1058, "Bractlet" },
            { 1059, "STULZ Air Technology Systems, Inc." },
            { 1060, "Climate Ready Engineering" },
            { 1061, "Genea Energy Partners" },
            { 1062, "IoTall Chile" },
            { 1063, "IKS Co., Ltd." },
            { 1064, "Yodiwo AB" },
            { 1065, "TITAN electronic GmbH" },
            { 1066, "IDEC Corporation" },
            { 1067, "SIFRI SL" },
            { 1068, "Thermal Gas Systems Inc." },
            { 1069, "Building Automation Products, Inc" },
            { 1070, "Asset Mapping" },
            { 1071, "Smarteh Company" },
            { 1072, "Datapod Australia Pty Ltd." },
            { 1073, "Buildings Alive Pty Ltd" },
            { 1074, "Digital Elektronik" },
            { 1075, "Talent Automacao e Tecnologia Ltda" },
            { 1076, "Norposh Limited" },
            { 1077, "Merkur Funksysteme AG" },
            { 1078, "Faster CZ spol. S.r.o" },
            { 1079, "Eco-Adapt" },
            { 1080, "Energocentrum Plus, s.r.o" },
            { 1081, "amBX UK Ltd" },
            { 1082, "Western Reserve Controls, Inc." },
            { 1083, "LayerZero Power Systems, Inc." },
            { 1084, "CIC Jan Hrebec s.r.o." },
            { 1085, "Sigrov BV" },
            { 1086, "ISYS-Intelligent Systems" },
            { 1087, "Gas Detection (Australia) Pty Ltd" },
            { 1088, "Kinco Automation (Shanghai) Ltd." },
            { 1089, "Lars Energy, LLC" },
            { 1090, "Flamefast (UK) Ltd." },
            { 1091, "Royal Service Air Conditioning" },
            { 1092, "Ampio Sp. Z o.o." },
            { 1093, "Inovonics Wireless Corporation" },
            { 1094, "Nvent Thermal Management" },
            { 1095, "Sinowell Control System Ltd." },
            { 1096, "Moxa Inc." },
            { 1097, "Matrix iControl SDN BHD" },
            { 1098, "PurpleSwift" },
            { 1099, "OTIM Technologies" },
            { 1100, "FlowMate Limited" },
            { 1101, "Degree Controls, Inc." },
            { 1102, "Fei Xing (Shanghai) Software Technologies Co., Ltd." },
            { 1103, "Berg GmbH" },
            { 1104, "ARENZ.IT" },
            { 1105, "Edelstrom Electronic Devices & Designing LLC" },
            { 1106, "Drive Connect, LLC" },
            { 1107, "DevelopNow" },
            { 1108, "Poort" },
            { 1109, "VMEIL Information (Shanghai) Ltd." },
            { 1110, "Rayleigh Instruments" },
            { 1111, "Reserved for ASHRAE" },
            { 1112, "CODEYSYS Development" },
            { 1113, "Smartware Technologies Group, LLC" },
            { 1114, "Polar Bear Solutions" },
            { 1115, "Codra" },
            { 1116, "Pharos Architectural Controls Ltd" },
            { 1117, "EngiNear Ltd." },
            { 1118, "Ad Hoc Electronics" },
            { 1119, "Unified Microsystems" },
            { 1120, "Industrieelektronik Brandenburg GmbH" },
            { 1121, "Hartmann GmbH" },
            { 1122, "Piscada" },
            { 1123, "KMB systems, s.r.o." },
            { 1124, "PowerTech Engineering AS" },
            { 1125, "Telefonbau Arthur Schwabe GmbH & Co. KG" },
            { 1126, "Wuxi Fistwelove Technology Co., Ltd." },
            { 1127, "Prysm" },
            { 1128, "STEINEL GmbH" },
            { 1129, "Georg Fischer JRG AG" },
            { 1130, "Make Develop SL" },
            { 1131, "Monnit Corporation" },
            { 1132, "Mirror Life Corporation" },
            { 1133, "Secure Meters Limited" },
            { 1134, "PECO" },
            { 1135, "CCTECH, Inc." },
            { 1136, "LightFi Limited" },
            { 1137, "Nice Spa" },
            { 1138, "Fiber SenSys, Inc." },
            { 1139, "B&D Buchta und Degeorgi" },
            { 1140, "Ventacity Systems, Inc." },
            { 1141, "Hitachi-Johnson Controls Air Conditioning, Inc." },
            { 1142, "Sage Metering, Inc." },
            { 1143, "Andel Limited" },
            { 1144, "ECOSmart Technologies" },
            { 1145, "S.E.T. Air Conditioning Engineering Co., Limited" },
            { 1146, "Protec Fire Detection Spain SL" },
            { 1147, "AGRAMER UG" },
            { 1148, "Anylink Electronic GmbH" },
            { 1149, "Schindler, Ltd" },
            { 1150, "Jibreel Abdeen Est." },
            { 1151, "Fluidyne Control Systems Pvt. Ltd" },
            { 1152, "Prism Systems, Inc." },
            { 1153, "Enertiv" },
            { 1154, "Mirasoft GmbH & Co. KG" },
            { 1155, "DUALTECH IT" },
            { 1156, "Countlogic, LLC" },
            { 1157, "Kohler" },
            { 1158, "Chen Sen Controls Co., Ltd." },
            { 1159, "Greenheck" },
            { 1160, "Intwine Connect, LLC" },
            { 1161, "Karlborgs Elkontroll" },
            { 1162, "Datakom" },
            { 1163, "Hoga Control AS" },
            { 1164, "Cool Automation" },
            { 1165, "Inter Search Co., Ltd" },
            { 1166, "DABBEL-Automation Intelligence GmbH" },
            { 1167, "Gadgeon Engineering Smartness" },
            { 1168, "Coster Group S.r.l." },
            { 1169, "Walter Mueller AG" },
            { 1170, "Fluke" },
            { 1171, "Quintex Systems Ltd" },
            { 1172, "Senfficient SDN BHD" },
            { 1173, "Nube iO Operations Pty Ltd" },
            { 1174, "DAS Integrator Pte Ltd" },
            { 1175, "CREVIS Co., Ltd" },
            { 1176, "iSquared software inc." },
            { 1177, "KTG GmbH" },
            { 1178, "POK Group Oy" },
            { 1179, "Adiscom" },
            { 1180, "Incusense" },
            { 1181, "75F" },
            { 1182, "Anord Mardix, Inc." },
            { 1183, "HOSCH Gebäudeautomation" },
            { 1184, "BOSCH Software Innovations GmbH" },
            { 1185, "Royal Boon Edam International B.V." },
            { 1186, "Clack Corporation" },
            { 1187, "Unitex Controls LLC" },
            { 1188, "KTC Göteborg AB" },
            { 1189, "Interzon AB" },
            { 1190, "ISDE ING SL" },
            { 1191, "ABM automation building messaging GmbH" },
            { 1192, "Kentec Electronics Ltd" },
            { 1193, "Emerson Commercial and Residential Solutions" },
            { 1194, "Powerside" },
            { 1195, "SMC Group" },
            { 1196, "EOS Weather Instruments" },
            { 1197, "Zonex Systems" },
            { 1198, "Generex Systems Computervertriebsgesellschaft mbH" },
            { 1199, "Energy Wall LLC" },
            { 1200, "Thermofin" },
            { 1201, "SDATAWAY SA" },
            { 1202, "Biddle Air Systems Limited" },
            { 1203, "Kessler" },
            { 1204, "Thermoscreens" },
            { 1205, "Modio" },
            { 1206, "Newron Solutions" },
            { 1207, "Unitronics" },
            { 1208, "TRILUX GmbH & Co. KG" },
            { 1209, "Kollmorgen Steuerungstechnik GmbH" },
            { 1210, "Bosch Rexroth AG" },
            { 1211, "Alarko Carrier" },
            { 1212, "Verdigris Technologies" },
            { 1213, "Shanghai SIIC-Longchuang Smarter Energy Technology Co., Ltd." },
            { 1214, "Quinda Co." },
            { 1215, "GRUNER AG" },
            { 1216, "BACMOVE" },
            { 1217, "PSIDAC AB" },
            { 1218, "ISICON-Control Automation" },
            { 1219, "Big Ass Fans" },
            { 1220, "din" },
            { 1221, "Teldio" },
            { 1222, "MIKROKLIMA s.r.o." },
            { 1223, "Density" },
            { 1224, "ICONAG-Leittechnik GmbH" },
            { 1225, "Awair" },
            { 1226, "T&D Engineering, Ltd" },
            { 1227, "Sistemas Digitales" },
            { 1228, "Loxone Electronics GmbH" },
            { 1229, "ActronAir" },
            { 1230, "Inductive Automation" },
            { 1231, "Thor Engineering GmbH" },
            { 1232, "Berner International, LLC" },
            { 1233, "Potsdam Sensors LLC" },
            { 1234, "Kohler Mira Ltd" },
            { 1235, "Tecomon GmbH" },
            { 1236, "Two Dimensional Instruments, LLC" },
            { 1237, "LEFA Technologies Pte. Ltd" },
            { 1238, "EATON CEAG Notlichtsysteme GmbH" },
            { 1239, "Commbox Tecnologia" },
            { 1240, "IPVideo Corporation" },
            { 1241, "Bender GmbH & Co. KG" },
            { 1242, "Rhymebus Corporation" },
            { 1243, "Axon Systems Ltd" },
            { 1244, "Engineered Air" },
            { 1245, "Elipse Software Ltd" },
            { 1246, "Simatix Building Technologies Pvt. Ltd." },
            { 1247, "W.A. Benjamin Electric Co." },
            { 1248, "TROX Air Conditioning Components (Suzhou) Co. Ltd." },
            { 1249, "SC Medical Pty Ltd." },
            { 1250, "Elcanic A/S" },
            { 1251, "Obeo AS" },
            { 1252, "Tapa, Inc." },
            { 1253, "ASE Smart Energy, Inc." },
            { 1254, "Performance Services, Inc." },
            { 1255, "Veridify Security" },
            { 1256, "CD Innovation LTD" },
            { 1257, "Ben Peoples Industries, LLC" },
            { 1258, "UNICOMM Sp. z o.o" },
            { 1259, "Thing Technologies GmbH" },
            { 1260, "Beijing HaiLin Energy Saving Technology, Inc." },
            { 1261, "Digital Realty" },
            { 1262, "Agrowtek Inc." },
            { 1263, "DSP Innovation BV " },
            { 1264, "STV Electronic GmbH" },
            { 1265, "Elmeasure India Pvt Ltd." },
            { 1266, "Pineshore Energy LLC." },
            { 1267, "Brasch Environmental Technologies, LLC." },
            { 1268, "Lion Controls Co., LTD" },
            { 1269, "Sinux" },
            { 1270, "Avnet Inc." },
            { 1271, "Somfy Activites SA" },
            { 1272, "Amico" },
            { 1273, "SageGlass" },
            { 1274, "AuVerte" },
            { 1275, "Agile Connects Pvt. Ltd." },
            { 1276, "Locimation Pty Ltd." },
            { 1277, "Envio Systems GmbH" },
            { 1278, "Voytech Systems Limited" },
            { 1279, "Davidsmeyer und Paul GmbH" },
            { 1280, "Lusher Engineering Services" },
            { 1281, "CHNT Nanjing Techsel Intelligent Company LTD." },
            { 1282, "Threetronics Pty Ltd." },
            { 1283, "SkyFoundry, LLC." },
            { 1284, "HanilProTech" },
            { 1285, "Sensorscall" },
            { 1286, "Shanghai Jingpu Information Technology, Co., Ltd." },
            { 1287, "Lichtmanufaktur Berlin GmbH" },
            { 1288, "Eco Parking Technologies" },
            { 1289, "Envision Digital International Pte Ltd." },
            { 1290, "Antony Developpement Electronique" },
            { 1291, "i2systems" },
            { 1292, "Thureon International Limited" },
            { 1293, "Pulsafeeder" },
            { 1294, "MegaChips Corporation" },
            { 1295, "TES Controls" },
            { 1296, "Cermate" },
            { 1297, "Grand Valley State University" },
            { 1298, "Symcon Gmbh" },
            { 1299, "The Chicago Faucet Company" },
            { 1300, "Geberit AG" },
            { 1301, "Rex Controls" },
            { 1302, "IVMS GmbH" },
            { 1303, "MNPP Saturn Ltd." },
            { 1304, "Regal Beloit" },
            { 1305, "ACS-Air Conditioning Solutions" },
            { 1306, "GBX Technology, LLC" },
            { 1307, "Kaiterra" },
            { 1308, "ThinKuan loT Technology (Shanghai) Co., Ltd" },
            { 1309, "HoCoSto B.V." },
            { 1310, "Shenzhen AS-AI Technology Co., Ltd." },
            { 1311, "RPS S.p.a." },
            { 1312, "Delta Dore Ems" },
            { 1313, "IOTech Systems Limited" },
            { 1314, "i-AutoLogic Co., Ltd." },
            { 1315, "New Age Micro, LLC" },
            { 1316, "Guardian Glass" },
            { 1317, "Guangzhou Zhaoyu Information Technology" },
            { 1318, "ACE IoT Solutions LLC" },
            { 1319, "Poris Electronics Co., Ltd." },
            { 1320, "Terminus Technologies Group" },
            { 1321, "Intech 21, Inc." },
            { 1322, "Accurate Electronics" },
            { 1323, "Fluence Bioengineering" },
            { 1324, "Mun Hean Singapore Pte Ltd" },
            { 1325, "Katronic AG & Co. KG" },
            { 1326, "Suzhou XinAo Information Technology Co. Ltd" },
            { 1327, "Linktekk Technology, JSC." },
            { 1328, "Stirling Ultracold" },
            { 1329, "UV Partners, Inc." },
            { 1330, "ProMinent GmbH" },
            { 1331, "Multi-Tech Systems, Inc." },
            { 1332, "JUMO GmbH & Co. KG" },
            { 1333, "Qingdao Huarui Technology Co. Ltd." },
            { 1334, "Cairn Systemes" },
            { 1335, "NeuroLogic Research Corp." },
            { 1336, "Transition Technologies Advanced Solutions Sp. z o.o" },
            { 1337, "Xxter bv" },
            { 1338, "PassiveLogic" },
            { 1339, "EnSmart Controls" },
            { 1340, "Watts Heating and Hot Water Solutions, dba Lync" },
            { 1341, "Troposphaira Technologies LLP" },
            { 1342, "Network Thermostat" },
            { 1343, "Titanium Intelligent Solutions, LLC" },
            { 1344, "Numa Products, LLC" },
            { 1345, "WAREMA Renkhoff SE" },
            { 1346, "Frese A/S" },
            { 1347, "Mapped" },
            { 1348, "ELEKTRODESIGN ventilatory s.r.o" },
            { 1349, "AirCare Automation, Inc." },
            { 1350, "Antrum" }
        };
        public static Dictionary<int, string> BACnetEngineeringUnits = new Dictionary<int, string>
        {
            { 0, "Sq Meters" },
            { 1, "Sq Feet" },
            { 2, "Milliamperes" },
            { 3, "Amperes" },
            { 4, "Ohms" },
            { 5, "Volts" },
            { 6, "Kilovolts" },
            { 7, "Megavolts" },
            { 8, "Volt Amperes" },
            { 9, "Kilovolt Amperes" },
            { 10, "Megavolt Amperes" },
            { 11, "Volt Amperes Reactive" },
            { 12, "Kilovolt Amperes Reactive" },
            { 13, "Megavolt Amperes Reactive" },
            { 14, "Degrees Phase" },
            { 15, "Power Factor" },
            { 16, "Joules" },
            { 17, "Kilojoules" },
            { 18, "Watt Hours" },
            { 19, "Kilowatt Hours" },
            { 20, "BTUs" },
            { 21, "Therms" },
            { 22, "Ton Hours" },
            { 23, "Joules Per Kg Dry Air" },
            { 24, "BTUs Per Pound Dry Air" },
            { 25, "Cycles Per Hour" },
            { 26, "Cycles Per Minute" },
            { 27, "Hertz" },
            { 28, "Grams Of Water Per Kilogram Dry Air" },
            { 29, "Relative Humidity" },
            { 30, "Millimeters" },
            { 31, "Meters" },
            { 32, "Inches" },
            { 33, "Feed" },
            { 34, "Watts Per Sq Foot" },
            { 35, "Watts Per Sq meter" },
            { 36, "Lumens" },
            { 37, "Lux" },
            { 38, "Foot Candles" },
            { 39, "Kilograms" },
            { 40, "Pounds Mass" },
            { 41, "Tons" },
            { 42, "Kgs per Second" },
            { 43, "Kgs Per Minute" },
            { 44, "Kgs Per Hour" },
            { 45, "Pounds Mass Per Minute" },
            { 46, "Pounds Mass Per Hour" },
            { 47, "Watt" },
            { 48, "Kilowatts" },
            { 49, "Megawatts" },
            { 50, "BTUs Per Hour" },
            { 51, "Horsepower" },
            { 52, "Tons Refrigeration" },
            { 53, "Pascals" },
            { 54, "Kilopascals" },
            { 55, "Bars" },
            { 56, "Pounds Force Per Square Inch" },
            { 57, "Centimeters Of Water" },
            { 58, "Inches Of Water" },
            { 59, "Millimeters Of Mercury" },
            { 60, "Centimeters Of Mercury" },
            { 61, "Inches Of Mercury" },
            { 62, "Degrees Celsius" },
            { 63, "Degrees Kelvin" },
            { 64, "Degrees Fahrenheit" },
            { 65, "Degree Days Celsius" },
            { 66, "Degree Days Fahrenheit" },
            { 67, "Years" },
            { 68, "Months" },
            { 69, "Weeks" },
            { 70, "Days" },
            { 71, "Hours" },
            { 72, "Minutes" },
            { 73, "Seconds" },
            { 74, "Meters Per Second" },
            { 75, "Kilometers Per Hour" },
            { 76, "Feed Per Second" },
            { 77, "Feet Per Minute" },
            { 78, "Miles Per Hour" },
            { 79, "Cubic Feet" },
            { 80, "Cubic Meters" },
            { 81, "Imperial Gallons" },
            { 82, "Liters" },
            { 83, "US Gallons" },
            { 84, "Cubic Feet Per Minute" },
            { 85, "Cubic Meters Per Second" },
            { 86, "Imperial Gallons Per Minute" },
            { 87, "Liters Per Second" },
            { 88, "Liters Per Minute" },
            { 89, "US Gallons Per Minute" },
            { 90, "Degrees Angular" },
            { 91, "Degrees Celsius Per Hour" },
            { 92, "Degrees Celsius Per Minute" },
            { 93, "Degrees Fahrenheit Per Hour" },
            { 94, "Degrees Fahrenheit Per Minute" },
            { 95, "No Units" },
            { 96, "Parts Per Million" },
            { 97, "Parts Per Billion" },
            { 98, "Percent" },
            { 99, "Percent Per Second" },
            { 100, "Per Minute" },
            { 101, "Per Second" },
            { 102, "Psi Per Degree Fahrenheit" },
            { 103, "Radians" },
            { 104, "Revolutions Per Min" },
            { 105, "Currency1" },
            { 106, "Currency2" },
            { 107, "Currency3" },
            { 108, "Currency4" },
            { 109, "Currency5" },
            { 110, "Currency6" },
            { 111, "Currency7" },
            { 112, "Currency8" },
            { 113, "Currency9" },
            { 114, "Currency10" },
            { 115, "Sq Inches" },
            { 116, "Sq Centimeters" },
            { 117, "BTUs Per Pound" },
            { 118, "Centimeters" },
            { 119, "Pounds Mass Per Second" },
            { 120, "Delta Degrees Fahrenheit" },
            { 121, "Delta Degrees Kelvin" },
            { 122, "Kilohms" },
            { 123, "Megohms" },
            { 124, "Millivolts" },
            { 125, "Kilojoules Per Kg" },
            { 126, "Megajoules" },
            { 127, "Joules Per Degree Kelvin" },
            { 128, "Joules Per Kg Degree Kelvin" },
            { 129, "Kilohertz" },
            { 130, "Megahertz" },
            { 131, "Per Hour" },
            { 132, "Milliwatts" },
            { 133, "Hectopascals" },
            { 134, "Millibars" },
            { 135, "Cubic Meters Per Hour" },
            { 136, "Liters Per Hour" },
            { 137, "KWatt Hours Per Square Meter" },
            { 138, "KWatt Hours Per Square Foot" },
            { 139, "Megajoules Per Square Meter" },
            { 140, "Megajoules Per Square Foot" },
            { 141, "Watts Per Sq Meter Degree Kelvin" },
            { 142, "Cubic Feet Per Second" },
            { 143, "Percent Obstruction Per Foot" },
            { 144, "Percent Obstruction Per Meter" },
            { 145, "milliohms" },
            { 146, "megawatt-hours" },
            { 147, "kilo-btus" },
            { 148, "mega-btus" },
            { 149, "kilojoules-per-kilogram-dry-air" },
            { 150, "megajoules-per-kilogram-dry-air" },
            { 151, "kilojoules-per-degree-Kelvin" },
            { 152, "megajoules-per-degree-Kelvin" },
            { 153, "newton" },
            { 154, "grams-per-second" },
            { 155, "grams-per-minute" },
            { 156, "tons-per-hour" },
            { 157, "kilo-btus-per-hour" },
            { 158, "hundredths-seconds" },
            { 159, "milliseconds" },
            { 160, "newton-meters" },
            { 161, "millimeters-per-second" },
            { 162, "millimeters-per-minute" },
            { 163, "meters-per-minute" },
            { 164, "meters-per-hour" },
            { 165, "cubic-meters-per-minute" },
            { 166, "meters-per-second-per-second" },
            { 167, "amperes-per-meter" },
            { 168, "amperes-per-square-meter" },
            { 169, "ampere-square-meters" },
            { 170, "farads" },
            { 171, "henrys" },
            { 172, "ohm-meters" },
            { 173, "siemens" },
            { 174, "siemens-per-meter" },
            { 175, "teslas" },
            { 176, "volts-per-degree-Kelvin" },
            { 177, "volts-per-meter" },
            { 178, "webers" },
            { 179, "candelas" },
            { 180, "candelas-per-square-meter" },
            { 181, "degrees-Kelvin-per-hour" },
            { 182, "degrees-Kelvin-per-minute" },
            { 183, "joule-seconds" },
            { 184, "radians-per-second" },
            { 185, "square-meters-per-Newton" },
            { 186, "kilograms-per-cubic-meter" },
            { 187, "newton-seconds" },
            { 188, "newtons-per-meter" },
            { 189, "watts-per-meter-per-degree-Kelvin" },
            { 190, "micro-siemens" },
            { 191, "cubic-feet-per-hour" },
            { 192, "us-gallons-per-hour" },
            { 193, "kilometers" },
            { 194, "micrometers" },
            { 195, "grams" },
            { 196, "milligrams" },
            { 197, "milliliters" },
            { 198, "milliliters-per-second" },
            { 199, "decibels" },
            { 200, "decibels-millivolt" },
            { 201, "decibels-volt" },
            { 202, "millisiemens" },
            { 203, "watt-hours-reactive" },
            { 204, "kilowatt-hours-reactive" },
            { 205, "megawatt-hours-reactive" },
            { 206, "millimeters-of-water" },
            { 207, "per-mille" },
            { 208, "grams-per-gram" },
            { 209, "kilograms-per-kilogram" },
            { 210, "grams-per-kilogram" },
            { 211, "milligrams-per-gram" },
            { 212, "milligrams-per-kilogram" },
            { 213, "grams-per-milliliter" },
            { 214, "grams-per-liter" },
            { 215, "milligrams-per-liter" },
            { 216, "micrograms-per-liter" },
            { 217, "grams-per-cubic-meter" },
            { 218, "milligrams-per-cubic-meter" },
            { 219, "micrograms-per-cubic-meter" },
            { 220, "nanograms-per-cubic-meter" },
            { 221, "grams-per-cubic-centimeter" },
            { 222, "becquerels" },
            { 223, "kilobecquerels" },
            { 224, "megabecquerels" },
            { 225, "gray" },
            { 226, "milligray" },
            { 227, "microgray" },
            { 228, "sieverts" },
            { 229, "millisieverts" },
            { 230, "microsieverts" },
            { 231, "microsieverts-per-hour" },
            { 232, "decibels-a" },
            { 233, "nephelometric-turbidity-unit" },
            { 234, "pH" },
            { 235, "grams-per-square-meter" },
            { 236, "minutes-per-degree-kelvin" },
            { 237, "ohm-meter-squared-per-meter" },
            { 238, "ampere-seconds" },
            { 239, "volt-ampere-hours" },
            { 240, "kilovolt-ampere-hours" },
            { 241, "megavolt-ampere-hours" },
            { 242, "volt-ampere-hours-reactive" },
            { 243, "kilovolt-ampere-hours-reactive" },
            { 244, "megavolt-ampere-hours-reactive" },
            { 245, "volt-square-hours" },
            { 246, "ampere-square-hours" },
            { 247, "joule-per-hours" },
            { 248, "cubic-feet-per-day" },
            { 249, "cubic-meters-per-day" },
            { 250, "watt-hours-per-cubic-meter" },
            { 251, "joules-per-cubic-meter" },
            { 252, "mole-percent" },
            { 253, "pascal-seconds" },
            { 254, "million-standard-cubic-feet-per-minute" },
            { 255, "unassigned-unit-value-255" },
            { 47808, "standard-cubic-feet-per-day" },
            { 47809, "million-standard-cubic-feet-per-day" },
            { 47810, "thousand-cubic-feet-per-day" },
            { 47811, "thousand-standard-cubic-feet-per-day" },
            { 47812, "pounds-mass-per-day" },
            { 47813, "reserved-unit-47813" },
            { 47814, "millirems" },
            { 47815, "millirems-per-hour" },
            { 47816, "degrees-lovibond" },
            { 47817, "alcohol-by-volume" },
            { 47818, "international-bittering-units" },
            { 47819, "european-bitterness-units" },
            { 47820, "degrees-plato" },
            { 47821, "specific-gravity" },
            { 47822, "european-brewing-convention" }
            /* Enumerated values 0-255 are reserved for definition by ASHRAE.
            Enumerated values 256-65535 may be used by others subject to
            the procedures and constraints described in Clause 23. */
        };
        public static Dictionary<int, string> BACnetEventState = new Dictionary<int, string>
        {
            { 0, "normal"},
            { 1, "fault"},
            { 2, "offnormal"},
            { 3, "high-limit"},
            { 4, "low-limit"},
            { 5, "live-safety-alarm"}
        };
        public static Dictionary<int, string> BACnetObjectType = new Dictionary<int, string>
        {
            {  0, "analog-input"},
            {  1, "analog-output"},
            {  2, "analog-value"},
            {  3, "binary-input"},
            {  4, "binary-output"},
            {  5, "binary-value"},
            {  6, "calendar"},
            {  7, "command"},
            {  8, "device"},
            {  9, "event-enrollment"},
            { 10, "file"},
            { 11, "group"},
            { 12, "loop"},
            { 13, "multi-state-input"},
            { 14, "multi-state-output"},
            { 15, "notification-class"},
            { 16, "program"},
            { 17, "schedule"},
            { 18, "averaging"},
            { 19, "multi-state-value"},
            { 20, "trend-log"},
            { 21, "life-safety-point"},
            { 22, "life-safety-zone"},
            { 23, "accumulator"},
            { 24, "pulse-converter"},
            { 25, "event-log"},
            { 26, "global-group"},
            { 27, "trend-log-multiple"},
            { 28, "load-control"},
            { 29, "structured-view"},
            { 30, "access-door"},     /* 30-37 added with addanda 135-2008j */
            { 31, "timer"},
            { 32, "access-credential"},
            { 33, "access-point"},
            { 34, "access-rights"},
            { 35, "access-user"},
            { 36, "access-zone"},
            { 37, "credential-data-input"},
            { 38, "network-security"},
            { 39, "bitstring-value"},     /* 39-50 added with addenda 135-2008w */
            { 40, "characterstring-value"},
            { 41, "date-pattern-value"},
            { 42, "date-value"},
            { 43, "datetime-pattern-value"},
            { 44, "datetime-value"},
            { 45, "integer-value"},
            { 46, "large-analog-value"},
            { 47, "octetstring-value"},
            { 48, "positive-integer-value"},
            { 49, "time-pattern-value"},
            { 50, "time-value"},
            { 51, "notification-forwarder"},
            { 52, "alert-enrollment"},
            { 53, "channel"},
            { 54, "lighting-output"},
            { 55, "binary-lighting-output"},
            { 56, "network-port"},
            { 57, "elevator-group"},
            { 58, "escalator"},
            { 59, "lift"},
            { 60, "staging"},
            { 61, "audit-log"},
            { 62, "audit-reporter"},
            { 63, "color"},
            { 64, "color-temperature"}
            /* Enumerated values 0-127 are reserved for definition by ASHRAE.
               Enumerated values 128-1023 may be used by others subject to
               the procedures and constraints described in Clause 23. */
        };
        public static Dictionary<int, string> BACnetReliability = new Dictionary<int, string>
        {
            {  0, "no-fault-detected"},
            {  1, "no-sensor"},
            {  2, "over-range"},
            {  3, "under-range"},
            {  4, "open-loop"},
            {  5, "shorted-loop"},
            {  6, "no-output"},
            {  7, "unreliable-other"},
            {  8, "process-error"},
            {  9, "multi-state-fault"},
            { 10, "configuration-error"},
            { 11, "reserved for a future addendum"},
            { 12, "communication-failure"},
            { 13, "member-fault"},
            { 14, "monitored-object-fault" },
            { 15, "tripped"},
            { 16, "lamp-failure"},
            { 17, "activation-failure"},
            { 18, "renew-dhcp-failure"},
            { 19, "renew-fd-registration-failure"},
            { 20, "restart-auto-negotiation-failure"},
            { 21, "restart-failure"},
            { 22, "proprietary-command-failure"},
            { 23, "faults-listed"},
            { 24, "referenced-object-fault"}
        };
        public static Dictionary<int, string> bvlc_function_names = new Dictionary<int, string>
        {
            {0x00, "BVLC-Result"},
            {0x01, "Write-Broadcast-Distribution-Table"},
            {0x02, "Read-Broadcast-Distribution-Table"},
            {0x03, "Read-Broadcast-Distribution-Table-Ack"},
            {0x04, "Forwarded-NPDU"},
            {0x05, "Register-Foreign-Device"},
            {0x06, "Read-Foreign-Device-Table"},
            {0x07, "Read-Foreign-Device-Table-Ack"},
            {0x08, "Delete-Foreign-Device-Table-Entry"},
            {0x09, "Distribute-Broadcast-To-Network"},
            {0x0a, "Original-Unicast-NPDU"},
            {0x0b, "Original-Broadcast-NPDU"},
            {0x0c, "Secured-BVLL"}
        };
        public static Dictionary<int, string> bvlc_ipv6_function_names = new Dictionary<int, string>
        {
            { 0x00, "BVLC-Result" },
            { 0x01, "Original-Unicast-NPDU" },
            { 0x02, "Original-Broadcast-NPDU" },
            { 0x03, "Address-Resolution" },
            { 0x04, "Forwarded-Address-Resolution" },
            { 0x05, "Address-Resolution-ACK" },
            { 0x06, "Virtual-Address-Resolution" },
            { 0x07, "Virtual-Address-Resolution-ACK" },
            { 0x08, "Forwarded-NPDU" },
            { 0x09, "Register-Foreign-Device" },
            { 0x0A, "Delete-Foreign-Device-Table-Entry" },
            { 0x0B, "Secure-BVLL" },
            { 0x0C, "Distribute-Broadcast-To-Network" }
        };
    }
}