namespace BACSender.Base.Enums
{
    // this needs to be transferred to a bitstring, see ISO16484-5 BACnetServicesSupported
    public enum BacnetSupportedServices
    {
        //ALARM AND EVENT SERVICES
        ACKNOWLEDGE_ALARM = 0,
        CONFIRMED_COV_NOTIFICATION = 1,
        CONFIRMED_COV_NOTIFICATION_MULTIPLE = 42,
        CONFIRMED_EVENT_NOTIFICATION = 2,
        GET_ALARM_SUMMARY = 3,
        GET_ENROLLMENT_SUMMARY = 4,
        GET_EVENT_INFORMATION = 39,
        LIFE_SAFETY_OPERATION = 37,
        SUBSCRIBE_COV = 5,
        SUBSCRIBE_COV_PROPERTY = 38,
        SUBSCRIBE_COV_PROPERTY_MULTIPLE = 41,

        //FILE ACCESS SERVICES
        ATOMIC_READ_FILE = 6,
        ATOMIC_WRITE_FILE = 7,

        //OBJECT ACCESS SERVICES
        ADD_LIST_ELEMENT = 8,
        REMOVE_LIST_ELEMENT = 9,
        CREATE_OBJECT = 10,
        DELETE_OBJECT = 11,
        READ_PROPERTY = 12,
        READ_PROPERTY_MULTIPLE = 14,
        READ_RANGE = 35,
        WRITE_GROUP = 40,
        WRITE_PROPERTY = 15,
        WRITE_PROPERTY_MULTIPLE = 16,

        //REMOTE DEVICE MANAGEMENT SERVICES
        DEVICE_COMMUNICATION_CONTROL = 17,
        CONFIRMED_PRIVATE_TRANSFER = 18,
        CONFIRMED_TEXT_MESSAGE = 19,
        REINITIALIZE_DEVICE = 20,

        //VIRTUAL TERMINAL SERVICES
        VT_OPEN = 21,
        VT_CLOSE = 22,
        VT_DATA = 23,


        //UNCONFIRMED SERVICES
        I_AM = 26,
        I_HAVE = 27,
        UNCONFIRMED_COV_NOTIFICATION = 28,
        UNCONFIRMED_COV_NOTIFICATION_MULTIPLE = 43,
        UNCONFIRMED_EVENT_NOTIFICATION = 29,
        UNCONFIRMED_PRIVATE_TRANSFER = 30,
        UNCONFIRMED_TEXT_MESSAGE = 31,
        TIME_SYNCHRONIZATION = 32,
        UTC_TIME_SYNCHRONIZATION = 36,
        WHO_HAS = 33,
        WHO_IS = 34

        ////REMOVED SERVICES
        //FORMERLY: READ_PROPERTY_CONDITIONAL = 13, REMOVED IN VERSION 1 REVISION 12 
        //FORMERLY: AUTHENTICATE = 24, REMOVED IN VERSION 1 REVISION 11 
        //FORMERLY: REQUEST_KEY = 25, REMOVED IN VERSION 1 REVISION 11 

        ////SERVICES ADDED AFTER 1995 
        //READ_RANGE = 35, // OBJECT ACCESS SERVICE
        //UTC_TIME_SYNCHRONIZATION = 36, // REMOTE DEVICE MANAGEMENT SERVICE
        //LIFE_SAFETY_OPERATION = 37,  //ALARM AND EVENT SERVICE
        //SUBSCRIBE_COV_PROPERTY = 38, // ALARM AND EVENT SERVICE
        //GET_EVENT_INFORMATION = 39, // ALARM AND EVENT SERVICE
        //WRITE_GROUP = 40, // OBJECT ACCESS SERVICES

        ////SERVICES ADDED AFTER 2012 
        //SUBSCRIBE_COV_PROPERTY_MULTIPLE = 41, __ ALARM AND EVENT SERVICE
        //CONFIRMED_COV_NOTIFICATION_MULTIPLE = 42, __ ALARM AND EVENT SERVICE
        //UNCONFIRMED_COV_NOTIFICATION_MULTIPLE = 43 __ ALARM AND EVENT SERVICE
    }
}
